<?php

namespace Tests\Feature\PackingList;

use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class ViewPackingListTest extends TestCase
{
    protected function setUp(): void
    {

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @test
     */
    public function it_shows_a_link_on_the_dashboard_that_calls_the_create_form_landingpage()
    {
        $user = User::factory()->forRole()->create();
        $this->actingAs($user);
        $url = route('packinglist.new');
        $this->get(route('dashboard'))
            ->assertSeeInOrder([
                $url,
                trans('packinglists.links.new')
            ]);
    }
}
